# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: "Differentially Private Statistical Models with SGD"
author: Max Ghenis
logo: logo.png
copyright: "2024"

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: cache
  timeout: 600
  allow_errors: false

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: statsmodels-sgd.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/PolicyEngine/statsmodels-sgd
  path_to_book: docs
  branch: main

# Add GitHub buttons to your book
html:
  use_issues_button: true
  use_repository_button: true
  use_edit_button: true
  
sphinx:
  extra_extensions:
    - sphinx.ext.autodoc
    - sphinx.ext.napoleon
    - sphinx.ext.viewcode
    - sphinxcontrib.bibtex
    - myst_nb
  config:
    html_theme: sphinx_book_theme
    html_theme_options:
      repository_url: "https://github.com/PolicyEngine/statsmodels-sgd"
      use_repository_button: true
      use_issues_button: true
      use_edit_button: true
      navigation_with_keys: true
    bibtex_reference_style: author_year
    
parse:
  myst_enable_extensions:
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution
    - tasklist